name: ESLint
on: [pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.0
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
